### PR TITLE
design of experiments

### PR DESCRIPTION
**Pull request by nikhar-abbas**
Delete the text explanations below these headers and replace them with information about your PR.
Please first consult the [developer guide](https://weis.readthedocs.io/en/latest/how_to_contribute_code.html) to make sure your PR follows all code, testing, and documentation conventions.

## Purpose
Enable the OpenMDAO based design of experiments capabilities. This involves changes to gc_PoseOptimization and the analysis_options yamls. 

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Added example 13 to test the design of experiments capabilities for blade chord. 

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [x] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation
   - I am not sure what documentation should be added here - let me know.

### CODE REVIEW

**Comment by ptrbortolotti** [comment]
@nikhar-abbas this is great. could you please just update the analysis schema for your new setup?

https://github.com/WISDEM/WISDEM/blob/27e59c6d4b00491a6e5f6338c36b09f11b174559/wisdem/inputs/analysis_schema.yaml#L790

**Comment by gbarter** [comment]
Nikhar- how comfortable are you with YAML schema?  I could do this fairly quickly if you need.

**Comment by nikhar-abbas** [comment]
> Nikhar- how comfortable are you with YAML schema? I could do this fairly quickly if you need.

I think I got it sorted, but you should definitely take a look at what I added. Lots of shooting from the hip going on over here...

**Review by gbarter — APPROVED** [review]
Really excited about that.  Everything looks good from my end.

**Pull request merged**
