### PR TITLE
3D correction airfoil polars + Tower mass + Logging

### PR DESCRIPTION
**Pull request by ptrbortolotti**
This PR reintroduces the 3d correction to airfoil polars, adds the outfitting factor to the tower mass distribution passed to weis, and brings in the logging package from GB. The PR also fixes an issue in rotor power where pitch in reg III was going negative
1. The 3d airfoil correction was (no longer?) part of the regular workflow. It was only called by the INN and by the DAC modules. In addition, the code wasn't being called correctly (chord_over_r factor was defined incorrectly, the AoA window was defined incorrectly) and I worked with Emmanuel to fix these issues. A flag in modeling options turns off the correction. The default is set to True.
Here a couple of examples for the corrections on the IEA15MW. Corrections are significant only inboard.

I will work with John to fix the correction in the INN branch.

2. The outfitting factor wasn't applied to the mass distribution that is later passed to weis. I will need to update wisdem into weis next.
3. The logging package was brought in by Garrett to handle infos, warnings and errors 
4. The IEA10 MW is a 1A machine with a tower height of 119 m
5. Region III was being resolved with a negative pitch trajectory. Now pitch can only grow in region III. Here there might still be an issue with reg II1/2 where power could go above rated. Nick has seen this issue in the SOAR rotor when n_pc is not very high. We might need to come up with an additional fix.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
I have updated the polar tests as well as the glue code tests because of the new polars and the tower tests for the outfitting factor.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by gbarter — COMMENTED** [review]
Thank you a bunch for the plots.  The orange line is the new results?  What is with the kink in the Cd plots- wouldn't that pose some problems for design?  There are also multiple 3d corrections available in AirfoilPreppy, right?  Those don't get called?  This is using Emmanuel's Polar class?

**Comment by ptrbortolotti** [comment]
I'll check in with EB about the kink in Cd. Polar and Airfoil preppy duplicate many things right now and should eventually be merged. I worked with Polar.py, but the 3d correction code was the same in both codes

**Comment by ptrbortolotti** [comment]
The kink probably pops up because the Viterna extension was applied BEFORE the 3d correction. The problem is that if I apply the extension after the correction, then the polars provided by the user would only be used in the linear region, whereas outside of this range they'd be totally neglected

**Comment by gbarter** [comment]
I remember going through this before.  The drag correction is slightly different between EB's [Polar](https://github.com/WISDEM/WISDEM/blob/develop/wisdem/ccblade/Polar.py#L184-L194) vs [AirfoilPreppy](https://github.com/WISDEM/WISDEM/blob/develop/wisdem/airfoilprep/airfoilprep.py#L171-L180).  Is it worth exploring if one way makes the kink and the other doesn't?  

I also don't quite follow the argument that if we extrapolate then correct vs correct then extrapolate.  The correction is also [looking for the linear region](https://github.com/WISDEM/WISDEM/blob/develop/wisdem/ccblade/Polar.py#L167).  If we extrapolate first, then much of the alpha-range won't be appropriately corrected.  Shouldn't we correct first and then extrapolate?

Am I causing you too many headaches?

**Comment by ptrbortolotti** [comment]
Emmanuel and I worked on this and we checked what other codes do. It turns out that Cd is usually not corrected, so I wrapped the cd correction into an if statement. We also implemented an additional smoothing function beside the Heaviside correction. Here the new plots

**Comment by ptrbortolotti** [comment]
If one wants to correct the drag, the best approach is to reapply the Veteran extension, but that likely changes the polars compared to the input ones

**Review by johnjasa — APPROVED** [review]

**Review by gbarter — APPROVED** [review]

**Pull request merged**
