### PR TITLE
Precommit hooks

### PR DESCRIPTION
**Pull request by gbarter**
Tried to follow tips from [here](https://medium.com/staqu-dev-logs/keeping-python-code-clean-with-pre-commit-hooks-black-flake8-and-isort-cac8b01e0ea1) and from the ORBIT repo, which has more hooks than this.  I think all you need to do, as a developer, is (from your local WISDEM clone):
`pip install pre-commit`
`pre-commit install`

This will likely need some tweaks as we start using it and get frustrated with various behaviors.

### CODE REVIEW

**Comment by johnjasa** [comment]
This is great!

I'm trying it out locally and ran into an issue when running the checks. Specifically, WISDEM code doesn't meet all of these checks as-is, so when a developer modifies a file, there are many errors in the pre-commit stack that aren't related to the change.

We could start with less stringent checks (Black only, maybe?) or reformulate code to avoid these issues, but that may be time-consuming. Or we could ask developers to fix any file as they come across it naturally. Definitely worth a discussion.

**Comment by gbarter** [comment]
Yes, agreed.  Can you either remove/comment out the checks that won't pass or copy over a screenshot so I can do so?

**Comment by johnjasa** [comment]
For sure, let me try to remove them on my end and push up.

For posterity, here's the output I'm seeing after modifying `runWISDEM.py`:

```(base) john@JJASA-35609S:/mnt/c/Users/jjasa/git/WISDEM/wisdem/glue_code$ git commit -am "Testing pre-commit hooks"
isort....................................................................Passed
black....................................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

wisdem/glue_code/runWISDEM.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: chmod -x wisdem/glue_code/runWISDEM.py
  If it is supposed to be executable, double-check its shebang.

Check JSON...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Flake8...................................................................Failed
- hook id: flake8
- exit code: 1

wisdem/glue_code/runWISDEM.py:23:1: C901 'run_wisdem' is too complex (16)
wisdem/glue_code/runWISDEM.py:28:121: E501 line too long (146 > 120 characters)
wisdem/glue_code/runWISDEM.py:29:121: E501 line too long (151 > 120 characters)
wisdem/glue_code/runWISDEM.py:42:121: E501 line too long (179 > 120 characters)

Mixed line ending........................................................Passed
Pretty format JSON...................................(no files to check)Skipped```

**Comment by johnjasa** [comment]
I've pushed up changes so the pre-commit stack ignores long comments, lack of shebangs on executables (appears to just be a Windows issue), and ignores cyclometric complexity warnings. I imagine there will be other codes we might run into as you mention in the original PR comment, so we can deal with those as needed.

**Review by johnjasa — APPROVED** [review]

**Comment by gbarter** [comment]
Thank you, John!

**Review by ptrbortolotti — APPROVED** [review]

**Pull request merged**
