### PR TITLE
Made3d

### PR DESCRIPTION
**Pull request by gbarter**
## Purpose
To help out Latha and Jon, I had to do a series of optimizations for the drivetrain and support structure with a detailed generator efficiency model.  To get it right, I realized I had to pull in changes I had been working on for Mike McWilliams (in the newsoil2 branch, new versions of the BOS codes, and some small upgrades to our generator modeling).  I had thought this project would involve small changes, but obviously they grew a bit.  Overall, the new WISDEM did a much better job than the old one.  

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

- [x] I have run existing tests which pass locally with my changes
- [x] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by johnjasa — APPROVED** [review]

**Comment by johnjasa** [comment]
This is a doozy, nice work! Glad ORBIT and LandBOSSE can be updated too.

**Review by ptrbortolotti — APPROVED** [review]
looks like great work! is the change of tolerances in rotor_power intended? What's the effect? shorter run times?

**Comment by gbarter** [comment]
Good catch, Pietro.  I had been experimenting with tolerances to reduce some optimization runtimes, but let me do some profiling and get back to you before we merge.

**Comment by gbarter** [comment]
It wasn't the tolerance slowing things down, so I reverted back to the old settings.  The rail_transport was activated for the reference turbine examples.  I turned that off, but should we consider creating a dedicated example for that?  I could see that feature falling out of sync if we don't use it and test it.

**Comment by ptrbortolotti** [comment]
I agree, the rail module should be kept off by default as it is pretty slow. I'll work on a dedicated test instead

**Pull request merged**
