### PR TITLE
Nopbeam

### PR DESCRIPTION
**Pull request by gbarter**
This turned into a slightly bigger feature branch than I was expecting.  Some points to note:

- pBeam is removed.  Frame3dd is used instead for the rotor loads analysis.  
- This was a relatively easy change for the standard rotor gust loading, but much more difficult for the rail transport case.  Because Frame3dd is more capable than pBeam, I could greatly simplify the code and workflow there.  However, a different approach now means that the BAR01 blade does not satisfy the derailing constraints. @ptrbortolotti : I think the bending solution you found previously does not necessarily correspond to a case where you can support the blade at other points on other train cars.  Please review the new code.  You and I will likely be iterating here.
- I have also used Frame3dd to identify the mode shapes for both the blade and tower.  This should obviate the use of BModes and CurveFEM as well.  However, I need help from @ptrbortolotti and @evan-gaertner to get these mode shapes into AeroelasticSE correctly.
- While updating the Extension compiling in setup.py, I also noticed that there were some community contributions to the CCBlade repo that fixed the gradients and simplified the API so that there are not 10 different output tuples/lists depending on the input flags.  I manually brought over these changes and made sure all of the tests were working.
- @johnjasa : The wisdem/test_ccblade/test_gradients.py doesn't test the gradients through the OpenMDAO components in ccblade_components.py, only in the direct bem solver wrapper.  I could use your help to make sure the gradients are correct there too.

Thanks for your help!

### CODE REVIEW

**Comment by johnjasa** [comment]
Great PR, I love the consolidation! I've examined [test_gradients.py](https://github.com/WISDEM/WISDEM/blob/nopbeam/wisdem/test/test_ccblade/test_gradients.py) and I'll create tests for the same functionality using the OM API from [ccblade_component.py](https://github.com/WISDEM/WISDEM/blob/nopbeam/wisdem/ccblade/ccblade_component.py) early this week.

Since there are so many tests in that file, I'll take care to make sure we're comparing at least as many values as before. Hopefully there aren't too many incorrect derivatives.

**Comment by gbarter** [comment]
Forgot to add that you will have to do `python setup.py develop` again to recompile PreComp as I had to add one more output for Frame3DD

**Comment by johnjasa** [comment]
I'm done updating the ccblade_component.py file and its derivatives. I added docstrings and some notes for possible later improvement. Those improvements should be part of a separate PR since they'll take a little bit of work, but it involves breaking up some of these components into a group of components to get rid of duplicated code.

**Comment by gbarter** [comment]
Thanks, John.  Pietro and I figured out the rail transport issues yesterday too.  I think the only remaining to-do item is to link the new blade and tower mode shapes and frequencies to AeroelasticSE.  I'm hesitant to merge this PR until we make those connections.

**Pull request merged**
