### PR TITLE
Ccblade deriv

### PR DESCRIPTION
**Pull request by gbarter**
## Purpose
Adding linearization for blade moment and also for all outputs wrt shearExp

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
- [x] I have run existing tests which pass locally with my changes
- [x] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gbarter** [comment]
I think I got everything taken care of here.  All of the tests, including all of the new added FD tests for the Moment & ShearExp gradients, are passing except for some of the OpenMDAO checks.  @johnjasa when you get a chance, I would appreciate your perspective if this is a tolerance issue or a true inaccuracy.

**Comment by johnjasa** [comment]
I examined the OM derivatives and found them to be of a large magnitude, causing a large absolute error between the calculated derivs and the finite-differenced derivs, but a reasonable relative error. Based on that, I loosened the absolute tolerance such that only the relative tolerance matters for those deriv tests. Here are some numbers from that test:

```
deriv of P wrt shearExp:
calculated deriv: -88264.68213139
FD deriv:         -88264.36568052
abs error:  0.316450878
rel error: 3.585262020762032e-06
```

I saw on the GH Actions workflow that there might be a drivetrain change that causes a test to fail: 
https://github.com/WISDEM/WISDEM/pull/268/checks?check_run_id=2372237894#step:7:783
Let me know if you want to resolve that, otherwise you'd probably be able to fix it easier.

Otherwise, looks great! Lot of changes, thank you for updating the testing throughout.

**Review by johnjasa — APPROVED** [review]

**Comment by gbarter** [comment]
Thank you, John!  Thank you also for pointing out that I accidentally co-mingled the drivetrain update for some 15MW support.  I fixed the bug and test, even though it should have gone in its own branch.

**Review by ptrbortolotti — APPROVED** [review]
one day you'll show me how you did it so quickly! thank you!

**Pull request merged**
