### PR TITLE
Modeshapes fix

### PR DESCRIPTION
**Pull request by nikhar-abbas**
This primarily offers an alternate method for calculating the modeshape coefficients after frame3dd is run. A few other minor bug fixes are sprinkled in as welll

## Purpose
This addresses an issue where a bad or zero modeshape would be passed to openfast in WEIS, and subsequently cause openfast to crash. An alternate (though still not perfect) method is used when `rank_and_file=True` in `get_xyz_modeshapes`. 

This guarantees that non-zero modeshapes will be output, and they will all "try" to be of the proper order, though if higher order mode is needed it will be used. This does _not_ guarantee that each modeshape is taken from a different frequency of calculation, as output from frame3dd.

Other bug fixes:
- re-add the step_calc option for finite differencing - I'm not sure where this got lost along the way
- use n_refine from the modeling options in towerse
 
## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by johnjasa — APPROVED** [review]
Thanks for this, @nikhar-abbas! I know it was a wild goose chase for a long time. I fully support this coming into WISDEM and will run some tower CCD cases with these changes on Eagle over the weekend.

**Comment by gbarter** [comment]
I'm glad this was more robust for your optimization problems.  To be honest, this is a lot of complexity and logic to wade through and I'm a little wary of maintaining it long-term.  Since this PR is just from one feature branch to another, it gives us some margin to work with it.  I see a lot of room for vectorization in the operations and it seems like a few code blocks are already implemented in the numpy [polynomial library](https://numpy.org/doc/stable/reference/routines.polynomials.polynomial.html).  My request is to add a unit test that exercises this capability so that we can merge the PR and then improve the code a bit while ensuring we are still getting the "right" answer.

**Comment by johnjasa** [comment]
Garrett, you're quite right about the maintainability. I spoke with Nikhar and I'll work to add a unit test early this week. Then we can merge this in feature branch to feature branch and later revisit the code complexity.

**Comment by gbarter** [comment]
The `full_frame` branch had some other fixes that were needed by the `develop` branch to overcome obstacles that were standing in the way of all WISDEM feature branches.  So, I did a PR for the `full_frame` content up to these changes here.  Now, we can bring in Nikhar's changes and deal with them exclusively.

**Comment by johnjasa** [comment]
I added a simple test for the `rank_and_file` method then took a few tries at simplifying the code. However, I haven't been able to fully simplify it and have the test pass (it's doing its job) so I'm tabling this for tonight.

**Comment by gbarter** [comment]
This is great, John.  You more than satisfied my nitpicky request.  Let's bring this into the WISDEM branch and continue to tinker a bit.

**Pull request merged**
