### PR TITLE
Loads from of

### PR DESCRIPTION
**Pull request by ptrbortolotti**
Open up rotor structure to be able to pass loads from OpenFAST in Eagle

## Purpose
Open up rotor structure to be able to pass loads from OpenFAST in Eagle

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
I changed the testing of rotor structure, removing the pbeam check and splitting the test for the two explicit components. Tests pass as long as openmdao is 3.8.0

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by gbarter** [comment]
OpenMDAO released 3.9.1 yesterday which I think may have fixed the issue too.  It usually takes ~24 for their conda package to update.

**Comment by ptrbortolotti** [comment]
we can wait to merge

**Review by gbarter — COMMENTED** [review]
Are you sure you want to move the `pbeam` flag?  That has been a helpful debugging tool.  Otherwise this looks good.

**Review by gbarter — APPROVED** [review]
THanks!

**Pull request merged**
