### PR TITLE
Analysis opts blade

### PR DESCRIPTION
**Pull request by ptrbortolotti**
I've changed the way the blade optimization works, removing the multiplicative (chord and spar caps) and additive (twist) gains and start optimizing the actual quantities parametrized at the n_opt locations. I've also added some new checks and I've simplified how the start and end indexing for DVs and constraints are set among the analysis options 

## Purpose
Simplify, clean, and improve the blade optimization options

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Standard tests are passing. Example 3 previously ran only a blade aero optimization, now also the struct and the aerostruct are run

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [x] I have added new tests or examples that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by ptrbortolotti** [comment]
part of the credit here should go to nick johnson for the never ending patience with WISDEM

**Comment by gbarter** [comment]
You spent a lot of time convincing us that optimization using these gains was a much better approach than optimizing the values directly.  I don't have an issue with what you have set up here, but it would be helpful to me to talk through it to make sure I understand it more fully.

**Comment by gbarter** [comment]
Also let me know if you need help resolving the conflicts.

**Review by gbarter — APPROVED** [review]
Spoke with Pietro and understand better now- thanks!

**Review by johnjasa — APPROVED** [review]
Talked with Pietro offline about the questions I had -- good to go!

**Comment by ptrbortolotti** [comment]
thank you for the reviews!

**Pull request merged**
