### PR TITLE
F/clean mod options

### PR DESCRIPTION
**Pull request by ptrbortolotti**
This PR does:
- Move the composite layer names from analysis options to modeling options. It also improves the error checking so that the code errors out only if the blade structure DV are set to True
- Groups the blade modeling options into RotorSE modeling options and the tower and monopoly modeling options into TowerSE modeling options
- Adds some descriptions to some of the analysis options flags

Tests should be passing and I tried to stick to the black coding style. 

It should be an easy ok

### CODE REVIEW

**Comment by ptrbortolotti** [comment]
I spoke too soon...

**Comment by gbarter** [comment]
BTW- If you install those pre-commit hooks, the Black compliant coding should be done for you (I think)

**Comment by johnjasa** [comment]
I see this passed tests but is still a draft -- @ptrbortolotti, do you plan to add to this or should I review for merging?

**Comment by ptrbortolotti** [comment]
it should be good to go now, thanks for the patience

**Review by johnjasa — APPROVED** [review]

**Review by gbarter — APPROVED** [review]

**Pull request merged**
