### PR TITLE
PCHIP interpolations for design optimization variables

### PR DESCRIPTION
**Pull request by cfrontin**
## Purpose

Currently, linear interpolation is used to map from the input initial rotor design to the set of equispaced control nodes along the blade for the optimization, including both active and inactive DoFs at the control nodes (the latter not being design variables and remaining unchanged in by the optimizer for all time).

This choice leads to significant interpolation errors that propagate to the optimizer results, especially when changing the number of control nodes along the span. Ideally, the initial geometry definitions would persist for all time in regions away from the region of active optimizer control; it is likely this is possible, although it would require a more significant and possibly fragile change. As an intermediate step, this change substitutes PCHIP interpolation for linear interpolation when the design variables (active & inactive) are set from on the initial values, which maintains the monotonicity of the linear interpolations while significantly improving the smoothness of the interpolation and its derivatives and conforming to typical spline/lofting conventions, e.g. [windIO](https://windio.readthedocs.io/en/latest/source/blade.html#outer-shape-bem).

## Type of change

- Breaking change (non-backwards-compatible fix or feature)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes

### CODE REVIEW

**Comment by ptrbortolotti** [comment]
I'm afraid you need to adjust the blade regression test "truth", maybe is,mply relaxing the tolerances

**Review by gbarter — APPROVED** [review]
Thank you for catching this inconsistency.

**Comment by cfrontin** [comment]
sorry to keep bothering you with re-reviews @gbarter and @ptrbortolotti, but I realized that my changes were not comprehensive at first; i've gone back in and changed more of the interpolations that come in from the yaml inputs and effect either the aerodynamic components or their structural equivalents. these changes required a bit more changes to the gold-standard values in the unit tests, mostly under 2% change w.r.t. the original value, but a handful larger, though never more than 5% different. the biggest offenders seem to have come from the blade material costs, which i think could get significant interpolation errors in some case. at any rate since this will have downstream effects and change estimates of some quantities by up to a few percent, i wanted to run it past y'all again.

**Review by gbarter — APPROVED** [review]
Added a minor question but otherwise looks good.  Thank you again for catching the interpolation inconsistency.

**Pull request merged**
