### PR TITLE
B/fix unsteady

### PR DESCRIPTION
**Pull request by gbarter**
## Purpose
Pietro- let me know if this is what you had in mind.  There would definitely be more room for cleanup if we used Emmanuel's code in other places.

## Type of change
What types of change is it?
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
- [x] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by ptrbortolotti — APPROVED** [review]
great job! much more elegant and robust

**Comment by ptrbortolotti** [comment]
we should remember that this will break openmdao_openfast.py

**Comment by gbarter** [comment]
How so?  I also tested this change in WEIS and it worked where the old code broke down. . .

**Comment by ptrbortolotti** [comment]
oh my internet is really buggy and tricked me. eval unsteady is still there, I missed the def and I thought you directly imported Polar.py. my bad!

**Pull request merged**
