### PR TITLE
Weis support

### PR DESCRIPTION
**Pull request by gbarter**
## Purpose
This is a good first draft of an overhaul to FloatingSE that can be included in the glue code and be better for WEIS support.  Since we were already warding off users from the old FloatingSE, it seems like this is a step in the right direction. 

More changes are likely to come, so I won't delete this branch yet, but the changes are accumulating, so better to get it into develop now.

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
- [x] I have run existing tests which pass locally with my changes
- [x] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by johnjasa — APPROVED** [review]
Is `substructure.py` no longer needed? I don't see it used in any Python file, but might be missing it.

**Comment by gbarter** [comment]
Is that what is bringing coveralls down?  I disconnected it for now but will use some of its code eventually.  I can delete it to avoid confusion.

**Comment by johnjasa** [comment]
Right, that's the main source of the coverage drop. If it's useful in the future, I'd say it's not an issue to keep it in there.

**Review by ptrbortolotti — APPROVED** [review]
good job Garrett! thank you for fixing the bugs I left behind and add all the new capabilities

**Pull request merged**
