### PR TITLE
Add peak thrust shaving to rotor_power

### PR DESCRIPTION
**Pull request by johnjasa**
## Purpose
This PR adds the option to set a coefficient on the max thrust to reduce that max thrust.
This is achieved within `rotor_power.py` by changing the sub-optimizations to be constrained by that shaved max thrust value.

Peak thrust shaving is still an experimental feature within WISDEM.

## Type of change
What types of change is it?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run existing tests which pass locally with my changes
- [x] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by gbarter — APPROVED** [review]
Thank you for jumping on this so quickly.  This will save everyone time in the long run.

**Comment by ptrbortolotti** [comment]
Thanks John for handling all this. The problem I see with the code that I wrote is that rotor_power has a nice logic where the wind speeds are not equally spaced between cut in and cut out but are refined around rated and more importantly the beginning of region II1.2 and III are exactly marked with a point in the grid. This is lost when the peak shaving option is turned on. If we decide to accept this approximation, which unless @gbarter proves me wrong, I don't think is very easy to overcome, we can merge

I'm also somewhat surprised by the discrepancy in omega that Eliot experiences. I wouldn't totally exclude that I messed something up with this code. Tomorrow I'll run some checks, so maybe we can wait a few hours before merging

**Comment by johnjasa** [comment]
I appreciate your additional context, Pietro. I'll sit tight on merging for now and we can check in together when you're ready.

**Comment by gbarter** [comment]
I didn't pick up on the changes in the wind speed grid.  I will take a closer look.

**Comment by gbarter** [comment]
I can see a pathway here where the peak shaving is more integrated into the power curve calculation.  Currently we have:

1. Solve Region II
2. Solve Region II.5 and rated
3. Solve Region III
4. Find max thrust and repeat Region II.5, rated, and Region III points that exceed threshold

Instead we could have:

1a. Solve Region II.5 and rated and max thrust without peak shaving
1b. Solve Region II.5 and rated with peak shaving, if necessary
2. Solve Region II (with peak shaving, if necessary)
3. Solve Region III (with peak shaving, if necessary)

This would involve some refactoring of the power curve calculation (again), but I could jump in there an do it if this sounds like the right way to go.

**Comment by ptrbortolotti** [comment]
It's true, we could wait to do reg III and do it after having done reg II1/2 without and with peak shaving. I'm not sure we can skip reg II and jump to II1/2 right away though. still, reg II is quick. shall I give it a shot?

**Comment by gbarter** [comment]
I've got it open now.  Let me take a turn and then confer with you.

**Comment by gbarter** [comment]
I checked in the approach I had in mind.  Please take a look and let me know what issues you see. 

@ptrbortolotti - The rated velocity should be the correct rated velocity with thrust shaving.  I still don't completely understand the velocity data point issue you had in mind

**Comment by ptrbortolotti** [comment]
I gave it a try and things seem to be all good!

**Review by ptrbortolotti — APPROVED** [review]

**Comment by gbarter** [comment]
What is the process for connecting this to WEIS?  Does Eliot's branch already have the right ROSCO and OpenFAST edits based on the modeling_input?

**Comment by johnjasa** [comment]
Those edits aren't currently in the WEIS version. I know @ptrbortolotti has been examining some issues regarding discrepancies between WISDEM and OpenFAST's powercurve computation when using thrust shaving. Pietro, does anything you've found affect how those changes to ROSCO and OF would be made?

**Comment by ptrbortolotti** [comment]
if G is ok I think we can merge, I haven't seen any specific problem with this PR

**Pull request merged**
